services:
  - type: web
    name: earning-boss-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT  # Render.com का पोर्ट डिटेक्ट करने के लिए जरूरी
        value: 10000  # या कोई भी पोर्ट (8000, 8080, 10000)
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: PROMO_CHANNEL
        sync: false
